//! Win32 bindings generated by `build.rs` with windows-bindgen.
//!
//! Generated code is exempt from the crate's lint policy: it is not
//! hand-written, and the `SAFETY:` comment rule and `unsafe_code` denial are
//! for code a reviewer is expected to read.

#![allow(
    unsafe_code,
    unsafe_op_in_unsafe_fn,
    dead_code,
    non_snake_case,
    non_camel_case_types,
    non_upper_case_globals,
    clippy::all,
    clippy::undocumented_unsafe_blocks
)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
